# Generated by Django 2.1.4 on 2018-12-22 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_app', '0008_auto_20181222_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateField(default='1999-04-05'),
        ),
    ]
