# Generated by Django 2.1.4 on 2018-12-22 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_app', '0010_auto_20181222_1600'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Event',
        ),
    ]
